// components/board/BoardConsentModal.tsx
//
// First-use informed-consent modal for the Board Confidence Analyzer. Unlike
// the app-wide ConsentModal (localStorage), this consent is persisted to
// member_board_records.consented_at and enforced SERVER-SIDE by the analyze
// route — declining leaves the page browsable but Run Analysis blocked.
//

"use client";

import BoardDisclaimer from "@/components/board/BoardDisclaimer";

export default function BoardConsentModal({
  onAccept,
  onDecline,
  saving,
}: {
  onAccept: () => void;
  onDecline: () => void;
  saving: boolean;
}) {
  return (
    <div className="apex-modal-overlay" role="dialog" aria-modal="true" aria-label="Record Readiness Review consent">
      <div className="w-full max-w-2xl p-8 rounded-2xl apex-card space-y-6 shadow-2xl max-h-[90vh] overflow-y-auto">
        <div
          className="space-y-2 border-b pb-4"
          style={{ borderColor: "var(--border)" }}
        >
          <h2 className="text-xl font-bold apex-heading tracking-wide">
            Record Readiness Review — Consent
          </h2>
          <p className="text-sm" style={{ color: "var(--muted-foreground)" }}>
            Before your first analysis, please review what this tool is and how
            your data is handled.
          </p>
        </div>

        <BoardDisclaimer />

        <div className="space-y-4 text-sm" style={{ color: "var(--foreground)" }}>
          <div>
            <strong className="apex-heading block mb-1">What an analysis processes:</strong>
            Your finalized APEX evaluations plus the record data you enter here
            (awards, NECs, education, PFA history, tours, LaDR checklist). The
            score itself is computed by a fixed, published rubric on this
            server — no AI is involved in the number.
          </div>
          <div>
            <strong className="apex-heading block mb-1">Optional AI narrative:</strong>
            When configured, the written strengths/gaps/recommendations are
            generated by an AI model selected by the administrator (e.g.
            Anthropic Claude, xAI Grok, or a locally hosted model) from the
            rubric&apos;s numeric output only — never your name, DoD ID,
            free-text entries, or uploaded documents. Without this, a
            deterministic narrative is produced locally.
          </div>
          <div>
            <strong className="apex-heading block mb-1">Storage and access:</strong>
            Your entries and each analysis snapshot are stored under your
            account only (row-level security; nobody else, including
            leadership, can run or view your analyses in this version). Full
            record content is never written to server logs. Uploaded record
            documents (ESR/PSR/OMPF) are session-ephemeral — they are
            destroyed when you log out — and must have PII redacted before
            upload.
          </div>
        </div>

        <div
          className="pt-6 flex flex-col-reverse sm:flex-row justify-end gap-3 border-t"
          style={{ borderColor: "var(--border)" }}
        >
          <button
            type="button"
            onClick={onDecline}
            className="apex-btn-secondary text-sm"
            disabled={saving}
          >
            Not now
          </button>
          <button
            type="button"
            onClick={onAccept}
            className="apex-btn-primary text-sm disabled:opacity-50"
            disabled={saving}
          >
            {saving ? "Saving…" : "I understand and consent"}
          </button>
        </div>
      </div>
    </div>
  );
}
